import React from 'react'
import {Shield,Users,Building,Target,Award} from 'lucide-react'
export default function About(){return(
  <div className="p-4 lg:p-6 space-y-6 max-w-4xl">
    <div className="bg-gradient-to-r from-emerald-700 to-emerald-900 rounded-2xl p-6 text-white"><div className="flex items-center gap-3 mb-4"><Shield className="w-10 h-10 text-emerald-300"/><div><h1 className="text-2xl font-bold">DengueSHIELD</h1><p className="text-emerald-300 text-sm">Surveillance, Health Informatics, and Evidence-Led Defense</p></div></div><p className="text-emerald-100 leading-relaxed">A web-based community participatory vector control platform integrating climate-responsive dengue surveillance for dengue hotspot barangays in Iloilo City. Funded by WVHRDC / DOST-GIA.</p></div>
    <div className="bg-white rounded-xl shadow-sm border p-5"><h2 className="font-bold text-lg mb-3 flex items-center gap-2"><Target className="w-5 h-5 text-emerald-600"/>NUHRA 2023\u20132028 Alignment</h2><div className="grid sm:grid-cols-2 gap-2">{['Disease Management','Health Security, Emergency, & DRM','Health Technology & Innovation','Health Promotion','Health Systems Strengthening towards UHC','Health of Vulnerable Populations'].map(t=>(<div key={t} className="flex items-center gap-2 bg-emerald-50 rounded-lg px-3 py-2"><div className="w-2 h-2 rounded-full bg-emerald-500"/><span className="text-sm">{t}</span></div>))}</div><p className="text-xs text-gray-500 mt-3">SDGs: 3 \u2022 9 \u2022 11 \u2022 13 \u2022 17</p></div>
    <div className="bg-white rounded-xl shadow-sm border p-5"><h2 className="font-bold text-lg mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-emerald-600"/>Project Team</h2><div className="space-y-3">{[{n:'Resti Tito H. Villarino, Dev.Ed.D, RN, LPT',r:'Project Leader',o:'WVSU CON',d:'NRCP Regular \u2022 40+ pubs \u2022 7-country collaborations'},{n:'Maureen Lorence F. Villarino, MA.Ed., RN, LPT',r:'Co-PI 1',o:'WVSU CON',d:'NRCP Associate \u2022 AMOMA co-developer'},{n:'Ryan Michael F. Oducado, PhD, MAN, MAEd, RN, RM, LPT, RGC',r:'Co-PI 2',o:'WVSU Research Director',d:'World Top 2% Scientist (Stanford 2023-24) \u2022 Scopus H:18 \u2022 2,725+ cites'},{n:'Ayesha C. Penuela, PhD, MAN, RN, LPT',r:'Co-PI 3',o:'WVSU CON Research Coordinator',d:'Outstanding Researcher 2025 \u2022 GSPNRI BOT \u2022 URERC Consultant'},{n:'Jing Hu, MSc., PhD Candidate',r:'Int\u2019l Advisor (Unfunded)',o:'UBO, Brest, France',d:'DPO, SCOT-DT Horizon Europe'}].map(p=>(<div key={p.n} className="border rounded-lg p-3"><p className="font-semibold text-sm">{p.n}</p><p className="text-xs text-emerald-600 font-medium">{p.r} \u2014 {p.o}</p><p className="text-xs text-gray-500 mt-1">{p.d}</p></div>))}</div></div>
    <div className="bg-white rounded-xl shadow-sm border p-5"><h2 className="font-bold text-lg mb-4 flex items-center gap-2"><Building className="w-5 h-5 text-emerald-600"/>Partners</h2><div className="grid sm:grid-cols-2 gap-3">{[{n:'WVSU College of Nursing',r:'Implementing Agency'},{n:'Iloilo City Health Office',r:'Technical supervision, epi data'},{n:'DOH \u2013 Western Visayas',r:'Lab services, training'},{n:'LGU Iloilo City',r:'Community mobilization'},{n:'RESU Region VI',r:'Surveillance support'},{n:'UBO, Brest, France',r:'International advisory'}].map(p=>(<div key={p.n} className="border rounded-lg p-3"><p className="font-medium text-sm">{p.n}</p><p className="text-xs text-gray-500">{p.r}</p></div>))}</div></div>
    <div className="bg-white rounded-xl shadow-sm border p-5"><h2 className="font-bold text-lg mb-3 flex items-center gap-2"><Award className="w-5 h-5 text-emerald-600"/>Platform Modules</h2><div className="space-y-2">{[{m:'Module 1: GIS Breeding Site Mapping',d:'GPS, geotagged photos, risk classification'},{m:'Module 2: Climate-Responsive Dashboard',d:'PAGASA rainfall/temp/humidity + BI/CI/HI/PPI'},{m:'Module 3: AI Risk Stratification',d:'Logistic regression on 6yr ICHO/PAGASA data'},{m:'Module 4: CBPLA Digital Learning',d:'5 modules in Hiligaynon with action cycles'},{m:'Module 5: Community Reporting',d:'Mobile-friendly, offline-capable, GPS auto-tag'}].map(x=>(<div key={x.m} className="p-3 bg-gray-50 rounded-lg"><p className="font-medium text-sm">{x.m}</p><p className="text-xs text-gray-600">{x.d}</p></div>))}</div></div>
    <p className="text-center text-xs text-gray-400 py-4">\u00a9 2026 WVSU College of Nursing \u2022 WVHRDC/DOST-GIA \u2022 Sep 2026\u2013Sep 2027</p>
  </div>
)}
