import React from 'react'
import {CheckCircle,Clock,Lock,ChevronRight} from 'lucide-react'
import {cbplaModules} from '../data/sampleData'
const si={completed:CheckCircle,in_progress:Clock,locked:Lock}
const sc={completed:'text-green-500',in_progress:'text-blue-500',locked:'text-gray-400'}
export default function CBPLAModules(){
  const tl=cbplaModules.reduce((a,m)=>a+m.lessons,0),cl=cbplaModules.reduce((a,m)=>a+Math.round(m.lessons*m.progress/100),0)
  return(
    <div className="p-4 lg:p-6 space-y-6">
      <div><h1 className="text-2xl font-bold text-gray-900">CBPLA Digital Learning Modules</h1><p className="text-sm text-gray-500">Culturally adapted in Hiligaynon/Filipino</p></div>
      <div className="bg-gradient-to-r from-emerald-50 to-emerald-100 rounded-xl border border-emerald-200 p-5"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><p className="text-sm text-emerald-700 font-medium">Overall Progress</p><p className="text-3xl font-bold text-emerald-900 mt-1">{cl}/{tl} Lessons</p><p className="text-sm text-emerald-600">{Math.round(cl/tl*100)}% complete</p></div><div className="w-full sm:w-48"><div className="h-3 bg-emerald-200 rounded-full overflow-hidden"><div className="h-full bg-emerald-600 rounded-full" style={{width:`${cl/tl*100}%`}}/></div></div></div></div>
      <div className="grid gap-4">{cbplaModules.map((m,i)=>{const Icon=si[m.status];return(<div key={m.id} className={`bg-white rounded-xl shadow-sm border p-5 ${m.status==='locked'?'opacity-60':''}`}><div className="flex items-start gap-4"><div className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${m.status==='completed'?'bg-green-100':m.status==='in_progress'?'bg-blue-100':'bg-gray-100'}`}><span className="text-lg font-bold text-gray-700">{i+1}</span></div><div className="flex-1"><div className="flex items-start justify-between"><div><h3 className="font-semibold text-gray-900 text-lg">{m.title}</h3><p className="text-sm text-gray-500">{m.titleEn}</p></div><Icon className={`w-5 h-5 ${sc[m.status]}`}/></div><p className="text-sm text-gray-600 mt-2">{m.desc}</p><div className="mt-3 flex items-center gap-4"><div className="flex-1"><div className="flex justify-between text-xs text-gray-500 mb-1"><span>{m.lessons} lessons</span><span>{m.progress}%</span></div><div className="h-2 bg-gray-100 rounded-full overflow-hidden"><div className={`h-full rounded-full ${m.status==='completed'?'bg-green-500':'bg-blue-500'}`} style={{width:`${m.progress}%`}}/></div></div>{m.status!=='locked'&&<button className="flex items-center gap-1 text-sm font-medium text-emerald-600">{m.status==='completed'?'Review':'Continue'}<ChevronRight className="w-4 h-4"/></button>}</div></div></div></div>)})}</div>
      <div className="bg-white rounded-xl shadow-sm border p-5"><h3 className="font-semibold text-gray-900 mb-3">Action Cycle: Identify \u2192 Plan \u2192 Act \u2192 Reflect</h3><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[{s:'IDENTIFY',d:'Map sites, assess risks',c:'bg-blue-50 border-blue-200 text-blue-800'},{s:'PLAN',d:'Prioritize, assign tasks',c:'bg-amber-50 border-amber-200 text-amber-800'},{s:'ACT',d:'Cleanup, education, reporting',c:'bg-green-50 border-green-200 text-green-800'},{s:'REFLECT',d:'Review data, adjust',c:'bg-purple-50 border-purple-200 text-purple-800'}].map(x=>(<div key={x.s} className={`rounded-lg border p-3 ${x.c}`}><p className="font-bold text-sm">{x.s}</p><p className="text-xs mt-1">{x.d}</p></div>))}</div></div>
    </div>
  )
}
