import React,{useState} from 'react'
import {MessageSquare,Plus,CheckCircle,Clock,AlertCircle,Send} from 'lucide-react'
import {communityReports} from '../data/sampleData'
const cfg={Verified:{icon:CheckCircle,c:'text-green-500 bg-green-50'},Resolved:{icon:CheckCircle,c:'text-green-500 bg-green-50'},Referred:{icon:AlertCircle,c:'text-blue-500 bg-blue-50'},Pending:{icon:Clock,c:'text-amber-500 bg-amber-50'},Noted:{icon:MessageSquare,c:'text-gray-500 bg-gray-50'}}
export default function CommunityReports(){
  const[show,setShow]=useState(false)
  return(
    <div className="p-4 lg:p-6 space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">Community Reports</h1><p className="text-sm text-gray-500">Household and BHW reporting system</p></div><button onClick={()=>setShow(!show)} className="bg-emerald-600 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2"><Plus className="w-4 h-4"/>New Report</button></div>
      {show&&<div className="bg-white rounded-xl shadow-sm border p-5"><h3 className="font-semibold mb-4">Submit New Report</h3><div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-gray-700 mb-1">Type</label><select className="w-full border rounded-lg px-3 py-2 text-sm"><option>Breeding Site</option><option>Suspected Case</option><option>Drainage Issue</option><option>Feedback</option></select></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Location</label><input type="text" placeholder="Purok, landmark" className="w-full border rounded-lg px-3 py-2 text-sm"/></div><div className="sm:col-span-2"><label className="block text-sm font-medium text-gray-700 mb-1">Description</label><textarea rows={3} placeholder="What did you observe?" className="w-full border rounded-lg px-3 py-2 text-sm"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Photo</label><input type="file" accept="image/*" className="w-full text-sm"/></div><div className="flex items-end"><button className="bg-emerald-600 text-white px-6 py-2 rounded-lg text-sm font-medium flex items-center gap-2"><Send className="w-4 h-4"/>Submit</button></div></div></div>}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{l:'Total',v:communityReports.length,c:'bg-gray-100'},{l:'Verified/Resolved',v:communityReports.filter(r=>r.status==='Verified'||r.status==='Resolved').length,c:'bg-green-100'},{l:'Pending',v:communityReports.filter(r=>r.status==='Pending').length,c:'bg-amber-100'},{l:'Referred',v:communityReports.filter(r=>r.status==='Referred').length,c:'bg-blue-100'}].map(s=>(<div key={s.l} className={`${s.c} rounded-xl p-4`}><p className="text-2xl font-bold">{s.v}</p><p className="text-sm text-gray-600">{s.l}</p></div>))}</div>
      <div className="bg-white rounded-xl shadow-sm border"><div className="p-4 border-b"><h3 className="font-semibold">Recent Reports</h3></div><div className="divide-y">{communityReports.map(r=>{const cf=cfg[r.status]||cfg.Noted;const Icon=cf.icon;return(<div key={r.id} className="p-4 hover:bg-gray-50"><div className="flex items-start gap-3"><div className={`p-1.5 rounded-lg ${cf.c}`}><Icon className="w-4 h-4"/></div><div className="flex-1"><div className="flex items-start justify-between"><div><p className="font-medium text-sm">{r.type} \u2014 {r.reporter}</p><p className="text-xs text-gray-500">{r.location} \u2022 {r.date}</p></div><span className={`text-xs font-medium px-2 py-0.5 rounded-full ${r.status==='Verified'||r.status==='Resolved'?'bg-green-100 text-green-700':r.status==='Pending'?'bg-amber-100 text-amber-700':'bg-blue-100 text-blue-700'}`}>{r.status}</span></div><p className="text-sm text-gray-600 mt-1">{r.response}</p></div></div></div>)})}</div></div>
    </div>
  )
}
