import React from 'react'
import {AlertTriangle} from 'lucide-react'
import {RadarChart,Radar,PolarGrid,PolarAngleAxis,PolarRadiusAxis,ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts'
import {riskZones} from '../data/sampleData'
const rf=[{factor:'Containers',p1:90,p4:25},{factor:'Drainage',p1:85,p4:20},{factor:'KAP(inv)',p1:80,p4:30},{factor:'PopDensity',p1:70,p4:35},{factor:'Rainfall',p1:75,p4:50},{factor:'History',p1:95,p4:30}]
export default function RiskAssessment(){return(
  <div className="p-4 lg:p-6 space-y-6">
    <div><h1 className="text-2xl font-bold text-gray-900">AI-Assisted Risk Stratification</h1><p className="text-sm text-gray-500">Logistic regression on ICHO/PAGASA data (2019\u20132024)</p></div>
    <div className="bg-gradient-to-r from-red-50 to-amber-50 rounded-xl border border-red-200 p-4"><div className="flex items-start gap-3"><AlertTriangle className="w-6 h-6 text-red-500 flex-shrink-0"/><div><p className="font-semibold text-red-800">Risk Level: ELEVATED</p><p className="text-sm text-red-700 mt-1">AI predicts elevated risk for next 2 weeks: rainfall 230mm, humidity 84%, BI 26 in Puroks 1 & 5.</p></div></div></div>
    <div className="grid lg:grid-cols-2 gap-6">
      <div className="bg-white rounded-xl shadow-sm border p-4"><h3 className="font-semibold mb-3">Risk Score by Zone</h3><ResponsiveContainer width="100%" height={300}><BarChart data={riskZones} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" domain={[0,100]}/><YAxis dataKey="zone" type="category" width={120} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="score" fill="#ef4444" radius={[0,6,6,0]} label={{position:'right',fontSize:11}}/></BarChart></ResponsiveContainer></div>
      <div className="bg-white rounded-xl shadow-sm border p-4"><h3 className="font-semibold mb-3">Purok 1 (Critical) vs Purok 4 (Low)</h3><ResponsiveContainer width="100%" height={300}><RadarChart data={rf}><PolarGrid/><PolarAngleAxis dataKey="factor" tick={{fontSize:10}}/><PolarRadiusAxis angle={30} domain={[0,100]}/><Radar name="Purok 1" dataKey="p1" stroke="#dc2626" fill="#dc2626" fillOpacity={0.3}/><Radar name="Purok 4" dataKey="p4" stroke="#22c55e" fill="#22c55e" fillOpacity={0.3}/><Tooltip/></RadarChart></ResponsiveContainer></div>
    </div>
    <div className="bg-white rounded-xl shadow-sm border p-4"><h3 className="font-semibold mb-3">Zone Details</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50"><th className="p-3 text-left">Zone</th><th className="p-3">Risk</th><th className="p-3">Score</th><th className="p-3">HH</th><th className="p-3 text-left">Factors</th><th className="p-3 text-left">Action</th></tr></thead><tbody>{riskZones.map(z=>(<tr key={z.zone} className="border-t"><td className="p-3 font-medium">{z.zone}</td><td className="p-3 text-center"><span className={`px-2 py-1 rounded-full text-xs font-bold ${z.risk==='Critical'?'bg-red-100 text-red-700':z.risk==='High'?'bg-orange-100 text-orange-700':z.risk==='Moderate'?'bg-yellow-100 text-yellow-700':'bg-green-100 text-green-700'}`}>{z.risk}</span></td><td className="p-3 text-center font-bold">{z.score}</td><td className="p-3 text-center">{z.households}</td><td className="p-3 text-xs">{z.factors.join('; ')}</td><td className="p-3 text-xs">{z.risk==='Critical'?'Immediate cleanup + daily monitoring':z.risk==='High'?'Weekly surveillance':z.risk==='Moderate'?'Bi-weekly checks':'Maintain program'}</td></tr>))}</tbody></table></div></div>
  </div>
)}
